version: '3'

volumes:
  static:
  media:
  pg_data:

services:
  db:
    container_name: kitty-db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    container_name: kitty-backend
    build: ./backend
    env_file: .env
    volumes:
      - static:/app/web/backend_static
      - media:/app/web/mediafiles
    depends_on:
      - db
    command: sh -c "sleep 5 && ./run.sh"
    restart: always

  frontend:
    container_name: kitty-frontend
    build: ./frontend
    env_file: .env
    volumes:
      - static:/app/web/frontend_static
    command: cp -r /app/build/. /app/web/frontend_static
    restart: always

  gateway:
    container_name: kitty-gateway
    build: ./nginx
    env_file: .env
    volumes:
      - static:/web
      - media:/web/mediafiles
    ports:
      - 8000:80
    restart: always
